<?php

declare(strict_types=1);

namespace ShopwareGdprDump\Output;

final class PluginConfigDraftWriter
{
    /**
     * @param array{
     *   plugin: array<string, string>,
     *   tables: array<string, array<string, mixed>>,
     *   warnings: list<string>,
     *   todos: list<string>
     * } $draft
     */
    public function write(array $draft): string
    {
        $lines = [
            '# DRAFT — generated by bin/scan-plugin-migrations',
            '# Review carefully before committing. Remove this header.',
            '# Remove columns marked skip/review, resolve TODO comments, then run bin/cleanup-plugin-config.',
            '',
        ];

        foreach ($draft['warnings'] as $warning) {
            $lines[] = '# WARNING: ' . $warning;
        }

        if ($draft['warnings'] !== []) {
            $lines[] = '';
        }

        $lines[] = 'plugin:';
        foreach ($draft['plugin'] as $key => $value) {
            $lines[] = '  ' . $key . ': ' . $this->yamlScalar($value);
        }

        $lines[] = '';
        $lines[] = 'dump:';
        $lines[] = '  tables:';

        if ($draft['tables'] === []) {
            $lines[] = '    {}';
        } else {
            foreach ($draft['tables'] as $table => $config) {
                if (($config['_remove_table'] ?? false) === true) {
                    $comment = $config['_comment'] ?? 'matches remove heuristic';
                    $lines[] = '    # TODO: remove entire table before commit — ' . $comment;
                }

                $lines[] = '    ' . $this->yamlTableKey($table) . ':';

                if (isset($config['nodata']) && $config['nodata'] === true) {
                    $lines[] = '      nodata: true';
                }

                $rewrites = $config['rewrite'] ?? [];
                if ($rewrites === []) {
                    continue;
                }

                $lines[] = '      rewrite:';

                foreach ($this->orderRewriteColumns($rewrites) as $entry) {
                    $column = $entry['column'];
                    $value = $entry['value'];
                    $uncertain = ($config['_uncertain'][$column] ?? false) === true;

                    if ($value === 'skip') {
                        $lines[] = '        # ' . $column . ': skip — structural column, remove before commit';
                        continue;
                    }

                    if ($value === 'review') {
                        $lines[] = '        # TODO: review';
                        $lines[] = '        ' . $column . ': review';
                        continue;
                    }

                    if ($uncertain) {
                        $lines[] = '        # TODO: verify heuristic';
                    }

                    $lines[] = '        ' . $column . ': ' . $this->yamlScalar($value);
                }
            }
        }

        foreach ($draft['todos'] as $todo) {
            $lines[] = '# TODO: ' . $todo;
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @param array<string, string> $rewrites
     *
     * @return list<array{column: string, value: string, kind: string}>
     */
    private function orderRewriteColumns(array $rewrites): array
    {
        $guessed = [];
        $review = [];
        $skip = [];

        foreach ($rewrites as $column => $value) {
            $value = (string) $value;
            $entry = ['column' => (string) $column, 'value' => $value, 'kind' => 'guessed'];

            if ($value === 'skip') {
                $entry['kind'] = 'skip';
                $skip[(string) $column] = $entry;
                continue;
            }

            if ($value === 'review') {
                $entry['kind'] = 'review';
                $review[(string) $column] = $entry;
                continue;
            }

            $guessed[(string) $column] = $entry;
        }

        ksort($guessed);
        ksort($review);
        ksort($skip);

        return [...array_values($guessed), ...array_values($review), ...array_values($skip)];
    }

    private function yamlTableKey(string $table): string
    {
        if (preg_match('/^[a-z0-9_-]+$/i', $table) === 1) {
            return $table;
        }

        return $this->yamlScalar($table);
    }

    private function yamlScalar(string $value): string
    {
        if (preg_match('/^[a-z0-9_-]+$/i', $value) === 1) {
            return $value;
        }

        return '"' . addcslashes($value, "\\\"\n\r") . '"';
    }
}
