<?php

declare(strict_types=1);

namespace ShopwareGdprDump\Validate;

final class PluginFileQualityValidator
{
    /** @var list<string> */
    private const FORBIDDEN_PATTERNS = [
        'DRAFT — generated by bin/scan-plugin-migrations' => 'remove scanner draft header before committing',
        'Review carefully before committing. Remove this header.' => 'remove scanner draft header before committing',
    ];

    /**
     * @return list<string>
     */
    public function validate(string $file): array
    {
        $contents = file_get_contents($file);
        if ($contents === false) {
            return [sprintf('%s: unable to read file', $file)];
        }

        $errors = [];

        foreach (preg_split('/\R/', $contents) ?: [] as $index => $line) {
            $lineNumber = $index + 1;

            foreach (self::FORBIDDEN_PATTERNS as $pattern => $message) {
                if (str_contains($line, $pattern)) {
                    $errors[] = sprintf('%s:%d: %s', $file, $lineNumber, $message);
                }
            }

            if (preg_match('/#\s*TODO\b/i', $line) === 1) {
                $errors[] = sprintf('%s:%d: resolve or remove TODO before committing', $file, $lineNumber);
            }
        }

        return $errors;
    }
}
